services:
  mongo:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: mongo_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/mongo_data:/data/db
    ports:
      - "27017:27017"
  
  hangman-api:
    build:
      context: ./db-api
      dockerfile: Dockerfile
    container_name: hangman-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - ./db-api:/app
    environment:
      - MONGO_URI=${MONGO_URI_API}