version: '3.8'

services:
  mongo:
    build: ./database
    container_name: mongo_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/mongo_data:/data/db
    ports:
      - "27017:27017"