services:
  mongo:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: mongo_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/mongo_data:/data/db
    ports:
      - "27017:27017"
  
  hangman-api:
    build:
      context: ./db-api
      dockerfile: Dockerfile
    container_name: hangman-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - ./db-api:/app
    environment:
      - MONGO_URI=${MONGO_URI_API}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  mongo-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: ollama-container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "11434:11434"
    volumes:
      - ./llm:/app
  
  llm-api:
    build:
      context: ./llm-api
      dockerfile: Dockerfile
    container_name: llm-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - llm
    volumes:
      - ./llm-api:/app
    environment:
      - LLM_URI=${LLM_URI}